_BASE_: ../../maskformer2_R50_bs16_50ep.yaml
MODEL:
  GEOMETRIC_PREDICTOR:
    NAME: "GeometricTransformer"
    TASK: 'o'
    OCCLUSION_ON: True  # Inference only (can disable output even if ION is sticked to M2F)
TEST:
  OCCLUSION_EVALUATION: True
